const express = require('express')
const router = express.Router()
router.get('/:id',(request,response)=>{
    //   response.send("Mobile Application"+request.params.id)
      if(request.params.id=='1')
      response.send("Mobile App Development")
      else if(request.params.id=='2')
      response.send("Website Development")
      else if(request.params.id=='3')
      response.send("Software Development")
      else if(request.params.id=='4')
      response.send("Marketing")
      else if(request.params.id=='5')
      response.send("Service Provider")
      else if(request.params.id=='6')
      response.send("Hardware Service")
      else if(request.params.id=='7')
      response.send("Software Service")
      else if(request.params.id=='8')
      response.send("Digital Marketing")
      else if(request.params.id=='9')
      response.send("Harddisk Recovery")
      else if(request.params.id=='10')
      response.send("Technican")

})
module.exports = router